import { Locale } from "../types";

const zhPlaceNames: Record<string, string> = {
  China: "中国",
  Japan: "日本",
  "South Korea": "韩国",
  Portugal: "葡萄牙",
  Indonesia: "印度尼西亚",
  USA: "美国",
  "New Zealand": "新西兰",
  Singapore: "新加坡",
  Thailand: "泰国",
  France: "法国",
  Italy: "意大利",
  Spain: "西班牙",
  "United Kingdom": "英国",
  UAE: "阿联酋",
  Maldives: "马尔代夫",
  Greece: "希腊",
  Kyoto: "京都",
  Seoul: "首尔",
  Lisbon: "里斯本",
  Bali: "巴厘岛",
  "New York": "纽约",
  Queenstown: "皇后镇",
  Shanghai: "上海",
  Beijing: "北京",
  Chengdu: "成都",
  "Xi'an": "西安",
  Hangzhou: "杭州",
  Sanya: "三亚",
  Zhangjiajie: "张家界",
  Guilin: "桂林",
  "Hong Kong": "香港",
  Tokyo: "东京",
  Osaka: "大阪",
  Bangkok: "曼谷",
  Phuket: "普吉岛",
  Paris: "巴黎",
  Rome: "罗马",
  Barcelona: "巴塞罗那",
  London: "伦敦",
  Dubai: "迪拜",
  Santorini: "圣托里尼",
  "Arashiyama Mist Walk": "岚山雾色漫步",
  "Midnight Market Bites": "午夜市集美食线",
  "Golden Tram Viewpoints": "金色电车观景线",
  "Cliffside Reset Retreat": "海崖放松度假",
  "Soho Studio Crawl": "苏荷艺术工作室漫游",
  "Skyline Ridge Rush": "天际山脊冒险",
  "Bund Skyline Evening Walk": "外滩天际线夜游",
  "Forbidden City Heritage Loop": "故宫文化环线",
  "Panda Base Family Morning": "熊猫基地亲子上午",
  "Ancient Wall Cycling Route": "古城墙骑行路线",
  "West Lake Tea Shore": "西湖茶岸慢游",
  "Yalong Bay Resort Day": "亚龙湾度假日",
  "Avatar Mountain Glass Walk": "阿凡达山峰玻璃栈道",
  "Li River Karst Cruise": "漓江喀斯特游船",
  "Victoria Harbor Light Route": "维港灯影路线",
  "Shibuya Food & Design Crawl": "涩谷美食与设计漫游",
  "Dotonbori Street Food Night": "道顿堀夜间美食",
  "Gardens by the Bay Family Loop": "滨海湾花园亲子环线",
  "Temple & Street Food Route": "寺庙与街头美食路线",
  "Island Hopping Blue Day": "跳岛蓝色一日",
  "Montmartre Art Morning": "蒙马特艺术早晨",
  "Colosseum Ancient Core": "斗兽场古城核心线",
  "Gaudi Color Walk": "高迪色彩漫步",
  "South Bank Museum Day": "南岸博物馆日",
  "Marina Luxury Evening": "滨海奢华夜晚",
  "Overwater Villa Escape": "水上别墅假期",
  "Oia Sunset Terrace": "伊亚日落露台",
  "Kyoto Slow Weekend": "京都慢周末",
  "Lisbon Design Sprint": "里斯本设计短途",
  "Shanghai Family City Break": "上海亲子城市短途",
  "Fushimi Inari Taisha": "伏见稻荷大社",
  "Kiyomizu-dera": "清水寺",
  "Ninenzaka and Sannenzaka": "二年坂与三年坂",
  "Yasaka Shrine": "八坂神社",
  "Gion Shirakawa": "祇园白川",
  "Nishiki Market": "锦市场",
  "Arashiyama Bamboo Grove": "岚山竹林",
  "Tenryu-ji": "天龙寺",
  "Kinkaku-ji": "金阁寺",
  "Ryoan-ji": "龙安寺",
  "Nijo Castle": "二条城",
  "Philosopher's Path": "哲学之道",
  "The Bund": "外滩",
  "Yu Garden": "豫园",
  "City God Temple of Shanghai": "上海城隍庙",
  "Shanghai Museum": "上海博物馆",
  "People's Square": "人民广场",
  "Nanjing Road Pedestrian Street": "南京路步行街",
  "Oriental Pearl Tower": "东方明珠广播电视塔",
  "Shanghai Tower": "上海中心大厦",
  Tianzifang: "田子坊",
  Xintiandi: "新天地",
  "Jing'an Temple": "静安寺",
  "Longhua Temple": "龙华寺",
  "Forbidden City": "故宫",
  "Tiananmen Square": "天安门广场",
  "Jingshan Park": "景山公园",
  "Beihai Park": "北海公园",
  "Temple of Heaven": "天坛",
  "Lama Temple": "雍和宫",
  Nanluoguxiang: "南锣鼓巷",
  Shichahai: "什刹海",
  "Summer Palace": "颐和园",
  "Old Summer Palace": "圆明园",
  "798 Art District": "798 艺术区",
  "Mutianyu Great Wall": "慕田峪长城",
  "West Lake": "西湖",
  "Broken Bridge": "断桥",
  "Su Causeway": "苏堤",
  "Leifeng Pagoda": "雷峰塔",
  "Lingyin Temple": "灵隐寺",
  "Feilai Peak": "飞来峰",
  "Longjing Tea Village": "龙井茶村",
  "China National Tea Museum": "中国茶叶博物馆",
  "Hefang Street": "河坊街",
  "Hu Xueyan Former Residence": "胡雪岩故居",
  "Xixi National Wetland Park": "西溪国家湿地公园",
  "Grand Canal Hangzhou Section": "京杭大运河杭州段",
  "Yalong Bay": "亚龙湾",
  "Wuzhizhou Island": "蜈支洲岛",
  "Dadonghai Beach": "大东海",
  "Luhuitou Park": "鹿回头风景区",
  "Tianya Haijiao": "天涯海角",
  "Nanshan Cultural Tourism Zone": "南山文化旅游区",
  "Sanya Romance Park": "三亚千古情景区",
  "Sanya Bay Coconut Dream Corridor": "三亚湾椰梦长廊",
  "Haitang Bay": "海棠湾",
  "Atlantis Sanya Aquaventure": "三亚亚特兰蒂斯水世界",
  "Sanya International Duty Free City": "三亚国际免税城",
  "Yanoda Rainforest Cultural Tourism Zone": "呀诺达雨林文化旅游区",
  "Shibuya Crossing": "涩谷十字路口",
  "Meiji Jingu": "明治神宫",
  "Harajuku Takeshita Street": "原宿竹下通",
  Omotesando: "表参道",
  "Tokyo Tower": "东京塔",
  "Senso-ji": "浅草寺",
  "Nakamise-dori Street": "仲见世商店街",
  "Ueno Park": "上野公园",
  "Akihabara Electric Town": "秋叶原电器街",
  "Tsukiji Outer Market": "筑地场外市场",
  Ginza: "银座",
  "TeamLab Planets Tokyo": "东京 TeamLab Planets",
  "Gyeongbokgung Palace": "景福宫",
  "Bukchon Hanok Village": "北村韩屋村",
  Insadong: "仁寺洞",
  "Changdeokgung Palace": "昌德宫",
  "Gwangjang Market": "广藏市场",
  Myeongdong: "明洞",
  "N Seoul Tower": "N 首尔塔",
  "Namsan Park": "南山公园",
  "Dongdaemun Design Plaza": "东大门设计广场",
  "Cheonggyecheon Stream": "清溪川",
  "Hongdae Street": "弘大街区",
  "Starfield Library": "星空图书馆",
  "Gardens by the Bay": "滨海湾花园",
  "Cloud Forest": "云雾林",
  "Marina Bay Sands SkyPark": "滨海湾金沙空中花园",
  "Merlion Park": "鱼尾狮公园",
  "Chinatown Street Market": "牛车水街市",
  "Buddha Tooth Relic Temple": "佛牙寺龙华院",
  "Kampong Glam": "甘榜格南",
  "Haji Lane": "哈芝巷",
  "Little India": "小印度",
  "Singapore Botanic Gardens": "新加坡植物园",
  "Sentosa Siloso Beach": "圣淘沙西乐索海滩",
  "Jewel Changi Airport": "星耀樟宜",
  "Victoria Peak": "太平山顶",
  "Peak Tram": "山顶缆车",
  "Tsim Sha Tsui Promenade": "尖沙咀海滨长廊",
  "Avenue of Stars": "星光大道",
  "Star Ferry Pier": "天星码头",
  "Central Mid-Levels Escalator": "中环半山扶梯",
  "Man Mo Temple": "文武庙",
  "Tai Kwun": "大馆",
  "Temple Street Night Market": "庙街夜市",
  "Mong Kok Ladies' Market": "旺角女人街",
  "Nan Lian Garden": "南莲园池",
  "Tian Tan Buddha": "天坛大佛",
  "Chengdu Research Base of Giant Panda Breeding": "成都大熊猫繁育研究基地",
  "Wenshu Monastery": "文殊院",
  "People's Park": "人民公园",
  "Kuanzhai Alley": "宽窄巷子",
  "Jinli Ancient Street": "锦里古街",
  "Wuhou Shrine": "武侯祠",
  "Du Fu Thatched Cottage": "杜甫草堂",
  "Sichuan Museum": "四川博物院",
  "Taikoo Li Chengdu": "成都太古里",
  "IFS Chengdu": "成都 IFS",
  "Qingyang Palace": "青羊宫",
  "Eastern Suburb Memory": "东郊记忆",
  "Xi'an City Wall": "西安城墙",
  "Bell Tower of Xi'an": "西安钟楼",
  "Drum Tower of Xi'an": "西安鼓楼",
  "Muslim Quarter": "回民街",
  "Great Mosque of Xi'an": "西安大清真寺",
  "Shaanxi History Museum": "陕西历史博物馆",
  "Giant Wild Goose Pagoda": "大雁塔",
  "Da Tang Everbright City": "大唐不夜城",
  "Tang Paradise": "大唐芙蓉园",
  "Small Wild Goose Pagoda": "小雁塔",
  "Huaqing Palace": "华清宫",
  "Terracotta Army": "秦始皇帝陵兵马俑",
  "Praca do Comercio": "商业广场",
  "Lisbon Cathedral": "里斯本主教座堂",
  "Miradouro de Santa Luzia": "圣卢西亚观景台",
  "Sao Jorge Castle": "圣若热城堡",
  Alfama: "阿尔法玛",
  "Time Out Market Lisboa": "里斯本 Time Out 市场",
  "Belem Tower": "贝伦塔",
  "Jeronimos Monastery": "热罗尼莫斯修道院",
  "LX Factory": "LX 工厂",
  MAAT: "艺术、建筑与科技博物馆",
  "Eduardo VII Park": "爱德华七世公园",
  "Oceanario de Lisboa": "里斯本海洋馆",
  "Central Park": "中央公园",
  "The Metropolitan Museum of Art": "大都会艺术博物馆",
  "Times Square": "时代广场",
  "Bryant Park": "布莱恩特公园",
  "New York Public Library": "纽约公共图书馆",
  "Empire State Building": "帝国大厦",
  "Flatiron Building": "熨斗大厦",
  "Washington Square Park": "华盛顿广场公园",
  SoHo: "苏荷区",
  "Brooklyn Bridge": "布鲁克林大桥",
  DUMBO: "丹波区",
  "Chelsea Market": "切尔西市场",
  Dotonbori: "道顿堀",
  "Shinsaibashi-suji Shopping Street": "心斋桥筋商店街",
  "Kuromon Ichiba Market": "黑门市场",
  "Namba Yasaka Shrine": "难波八阪神社",
  "Osaka Castle": "大阪城",
  "Osaka Museum of History": "大阪历史博物馆",
  "Umeda Sky Building": "梅田蓝天大厦",
  "HEP Five Ferris Wheel": "HEP FIVE 摩天轮",
  "Shitenno-ji": "四天王寺",
  Tsutenkaku: "通天阁",
  Shinsekai: "新世界",
  "Tempozan Ferris Wheel": "天保山摩天轮",
  "Skyline Queenstown": "皇后镇天际缆车",
  "Queenstown Gardens": "皇后镇花园",
  "Lake Wakatipu Waterfront": "瓦卡蒂普湖滨",
  "TSS Earnslaw Steamship": "TSS 厄恩斯劳号蒸汽船",
  "Kiwi Park Queenstown": "皇后镇奇异鸟公园",
  "Shotover Jet": "沙特欧瓦喷射快艇",
  "Onsen Hot Pools": "温泉热池",
  "Arrowtown Historic Village": "箭镇历史村",
  "Gibbston Valley Winery": "吉布斯顿谷酒庄",
  "AJ Hackett Kawarau Bridge Bungy": "卡瓦劳大桥蹦极",
  "Bob's Cove Track": "鲍勃湾步道",
  "Glenorchy Wharf": "格林诺奇码头",
  "Zhangjiajie National Forest Park": "张家界国家森林公园",
  "Yuanjiajie Scenic Area": "袁家界景区",
  "Bailong Elevator": "百龙天梯",
  "Tianzi Mountain": "天子山",
  "Golden Whip Stream": "金鞭溪",
  "Ten-mile Gallery": "十里画廊",
  "Baofeng Lake": "宝峰湖",
  "Yellow Dragon Cave": "黄龙洞",
  "Zhangjiajie Grand Canyon Glass Bridge": "张家界大峡谷玻璃桥",
  "Tianmen Mountain": "天门山",
  "Tianmen Cave": "天门洞",
  "72 Strange Buildings": "七十二奇楼",
  "Elephant Trunk Hill": "象鼻山",
  "Two Rivers and Four Lakes": "两江四湖",
  "Sun and Moon Pagodas": "日月双塔",
  "Reed Flute Cave": "芦笛岩",
  "Seven Star Park": "七星公园",
  "Fubo Hill": "伏波山",
  "Duxiu Peak": "独秀峰",
  "East West Alley": "东西巷",
  "Longji Rice Terraces": "龙脊梯田",
  "Li River Cruise Pier": "漓江游船码头",
  "Xingping Ancient Town": "兴坪古镇",
  "West Street Yangshuo": "阳朔西街",
  "The Grand Palace": "大皇宫",
  "Wat Phra Kaew": "玉佛寺",
  "Wat Pho": "卧佛寺",
  "Wat Arun": "郑王庙",
  "Tha Maharaj": "塔玛哈拉码头文创区",
  "Pak Khlong Talat Flower Market": "帕空花市",
  "Chinatown Yaowarat": "耀华力唐人街",
  "Jim Thompson House": "吉姆汤普森故居",
  "MBK Center": "MBK 购物中心",
  "Lumphini Park": "伦披尼公园",
  "Chatuchak Weekend Market": "恰图恰周末市场",
  "Asiatique The Riverfront": "河滨夜市",
  "Patong Beach": "芭东海滩",
  "Bangla Road": "邦古拉街",
  "Karon Beach": "卡伦海滩",
  "Kata Beach": "卡塔海滩",
  "Big Buddha Phuket": "普吉大佛",
  "Wat Chalong": "查龙寺",
  "Phuket Old Town": "普吉老城",
  "Sunday Walking Street Market": "周日步行街夜市",
  "Promthep Cape": "神仙半岛",
  "Nai Harn Beach": "奈涵海滩",
  "Chillva Market": "青蛙夜市",
  "Ao Sane Beach": "奥森海滩",
  "Eiffel Tower": "埃菲尔铁塔",
  "Trocadero Gardens": "特罗卡德罗花园",
  "Louvre Museum": "卢浮宫",
  "Tuileries Garden": "杜乐丽花园",
  "Musee d'Orsay": "奥赛博物馆",
  "Notre-Dame Cathedral": "巴黎圣母院",
  "Sainte-Chapelle": "圣礼拜堂",
  "Le Marais": "玛黑区",
  "Place des Vosges": "孚日广场",
  "Sacré-Coeur": "圣心大教堂",
  Montmartre: "蒙马特",
  "Arc de Triomphe": "凯旋门",
  Colosseum: "罗马斗兽场",
  "Roman Forum": "古罗马广场",
  "Palatine Hill": "帕拉蒂尼山",
  "Piazza Venezia": "威尼斯广场",
  Pantheon: "万神殿",
  "Piazza Navona": "纳沃纳广场",
  "Trevi Fountain": "特莱维喷泉",
  "Spanish Steps": "西班牙阶梯",
  "Villa Borghese": "博尔盖塞别墅",
  "Borghese Gallery": "博尔盖塞美术馆",
  "Vatican Museums": "梵蒂冈博物馆",
  "St. Peter's Basilica": "圣彼得大教堂",
  "Sagrada Familia": "圣家堂",
  "Casa Batllo": "巴特罗之家",
  "La Pedrera Casa Mila": "米拉之家",
  "Park Guell": "古埃尔公园",
  "Gothic Quarter": "哥特区",
  "Barcelona Cathedral": "巴塞罗那主教座堂",
  "La Boqueria Market": "博盖利亚市场",
  "La Rambla": "兰布拉大道",
  "Palau de la Musica Catalana": "加泰罗尼亚音乐宫",
  "Montjuic Castle": "蒙锥克城堡",
  "Magic Fountain of Montjuic": "蒙锥克魔法喷泉",
  "Barceloneta Beach": "巴塞罗那塔海滩",
  "London Eye": "伦敦眼",
  "Southbank Centre": "南岸中心",
  "Westminster Abbey": "威斯敏斯特教堂",
  "Big Ben": "大本钟",
  "Trafalgar Square": "特拉法加广场",
  "National Gallery": "国家美术馆",
  "Covent Garden": "科文特花园",
  "British Museum": "大英博物馆",
  "Tower Bridge": "塔桥",
  "Tower of London": "伦敦塔",
  "Borough Market": "博罗市场",
  "Hyde Park": "海德公园",
  "Burj Khalifa": "哈利法塔",
  "Dubai Mall": "迪拜购物中心",
  "Dubai Fountain": "迪拜喷泉",
  "Museum of the Future": "未来博物馆",
  "Dubai Frame": "迪拜相框",
  "Al Fahidi Historical Neighbourhood": "阿法迪历史街区",
  "Dubai Creek": "迪拜河",
  "Gold Souk": "黄金市场",
  "Jumeirah Mosque": "朱美拉清真寺",
  "Kite Beach": "风筝海滩",
  "Dubai Marina Walk": "迪拜码头步道",
  "Palm Jumeirah Viewpoint": "朱美拉棕榈岛观景点",
  "Hulhumale Beach": "胡鲁马累海滩",
  "Male Fish Market": "马累鱼市",
  "Hukuru Miskiy": "星期五清真寺",
  "Sultan Park": "苏丹公园",
  "National Museum Maldives": "马尔代夫国家博物馆",
  "Artificial Beach": "人工海滩",
  "Villingili Public Beach": "维林吉利公共海滩",
  "Banana Reef": "香蕉礁",
  "Maafushi Bikini Beach": "马富施比基尼海滩",
  "Maafushi Island": "马富施岛",
  "Vaadhoo Island": "瓦度岛",
  "Thulusdhoo Island": "图鲁斯杜岛",
  "Oia Castle": "伊亚城堡",
  "Oia Blue Domes": "伊亚蓝顶教堂",
  "Ammoudi Bay": "阿穆迪湾",
  Fira: "费拉",
  "Three Bells of Fira": "费拉三钟教堂",
  "Museum of Prehistoric Thera": "史前锡拉博物馆",
  Imerovigli: "伊莫洛维里",
  "Skaros Rock": "斯卡洛斯岩",
  "Akrotiri Archaeological Site": "阿克罗蒂里考古遗址",
  "Red Beach": "红沙滩",
  "Perissa Black Sand Beach": "佩里萨黑沙滩",
  "Pyrgos Village": "皮尔戈斯村",
  "Uluwatu Temple": "乌鲁瓦图寺",
  "Padang Padang Beach": "巴东巴东海滩",
  "Garuda Wisnu Kencana": "神鹰广场",
  "Jimbaran Beach": "金巴兰海滩",
  "Tanah Lot": "海神庙",
  "Seminyak Beach": "水明漾海滩",
  "Ubud Monkey Forest": "乌布猴林",
  "Ubud Palace": "乌布皇宫",
  "Tegallalang Rice Terrace": "德格拉朗梯田",
  "Tirta Empul Temple": "圣泉寺",
  "Campuhan Ridge Walk": "坎普罕山脊步道",
  "Saraswati Temple": "萨拉斯瓦蒂寺",
};

export const placeText = (locale: Locale, value: string) => (locale === "zh" ? zhPlaceNames[value] ?? value : value);

export const placeLineText = (locale: Locale, value: string) =>
  value
    .split(" / ")
    .map((part) => placeText(locale, part))
    .join(" / ");
