const zhAliases: Record<string, string[]> = {
  China: ["中国"],
  Japan: ["日本"],
  "South Korea": ["韩国"],
  Portugal: ["葡萄牙"],
  Indonesia: ["印度尼西亚", "印尼"],
  USA: ["美国"],
  "New Zealand": ["新西兰"],
  Singapore: ["新加坡"],
  Thailand: ["泰国"],
  France: ["法国"],
  Italy: ["意大利"],
  Spain: ["西班牙"],
  "United Kingdom": ["英国"],
  UAE: ["阿联酋", "迪拜"],
  Maldives: ["马尔代夫"],
  Greece: ["希腊"],
  Kyoto: ["京都"],
  Seoul: ["首尔", "汉城"],
  Lisbon: ["里斯本"],
  Bali: ["巴厘岛"],
  "New York": ["纽约"],
  Queenstown: ["皇后镇"],
  Shanghai: ["上海"],
  Beijing: ["北京"],
  Chengdu: ["成都"],
  "Xi'an": ["西安", "西安市"],
  Hangzhou: ["杭州"],
  Sanya: ["三亚"],
  Zhangjiajie: ["张家界"],
  Guilin: ["桂林"],
  "Hong Kong": ["香港"],
  Tokyo: ["东京"],
  Osaka: ["大阪"],
  Bangkok: ["曼谷"],
  Phuket: ["普吉", "普吉岛"],
  Paris: ["巴黎"],
  Rome: ["罗马"],
  Barcelona: ["巴塞罗那"],
  London: ["伦敦"],
  Dubai: ["迪拜"],
  Santorini: ["圣托里尼"],
  "Arashiyama Mist Walk": ["岚山", "岚山竹林", "京都慢游"],
  "Midnight Market Bites": ["夜市", "首尔夜市", "广藏市场"],
  "Golden Tram Viewpoints": ["里斯本电车", "观景台"],
  "Cliffside Reset Retreat": ["海崖度假", "巴厘岛海景"],
  "Soho Studio Crawl": ["苏荷", "纽约画廊"],
  "Skyline Ridge Rush": ["皇后镇山脊", "天际缆车"],
  "Bund Skyline Evening Walk": ["外滩", "上海外滩", "黄浦江"],
  "Forbidden City Heritage Loop": ["故宫", "紫禁城", "北京故宫"],
  "Panda Base Family Morning": ["熊猫基地", "成都熊猫"],
  "Ancient Wall Cycling Route": ["西安城墙", "古城墙"],
  "West Lake Tea Shore": ["西湖", "龙井", "杭州西湖"],
  "Yalong Bay Resort Day": ["亚龙湾", "三亚海滩"],
  "Avatar Mountain Glass Walk": ["张家界森林公园", "阿凡达山", "玻璃桥"],
  "Li River Karst Cruise": ["漓江", "桂林山水"],
  "Victoria Harbor Light Route": ["维多利亚港", "维港", "星光大道"],
  "Shibuya Food & Design Crawl": ["涩谷", "涩谷十字路口"],
  "Dotonbori Street Food Night": ["道顿堀", "大阪美食"],
  "Gardens by the Bay Family Loop": ["滨海湾花园", "新加坡花园"],
  "Temple & Street Food Route": ["大皇宫", "曼谷寺庙"],
  "Island Hopping Blue Day": ["普吉跳岛", "芭东海滩"],
  "Montmartre Art Morning": ["蒙马特", "圣心大教堂"],
  "Colosseum Ancient Core": ["斗兽场", "罗马斗兽场"],
  "Gaudi Color Walk": ["高迪", "圣家堂", "巴塞罗那建筑"],
  "South Bank Museum Day": ["南岸", "伦敦眼"],
  "Marina Luxury Evening": ["迪拜码头", "哈利法塔"],
  "Overwater Villa Escape": ["水上别墅", "马代"],
  "Oia Sunset Terrace": ["伊亚", "圣托里尼日落"],
  "Fushimi Inari Taisha": ["伏见稻荷大社", "千本鸟居"],
  "Kiyomizu-dera": ["清水寺"],
  "Ninenzaka and Sannenzaka": ["二年坂", "三年坂"],
  "Yasaka Shrine": ["八坂神社"],
  "Gion Shirakawa": ["祇园白川", "祗园白川"],
  "Nishiki Market": ["锦市场"],
  "Arashiyama Bamboo Grove": ["岚山竹林"],
  "Tenryu-ji": ["天龙寺"],
  "Kinkaku-ji": ["金阁寺"],
  "The Bund": ["外滩"],
  "Yu Garden": ["豫园"],
  "City God Temple of Shanghai": ["上海城隍庙", "城隍庙"],
  "Shanghai Museum": ["上海博物馆"],
  "People's Square": ["人民广场"],
  "Nanjing Road Pedestrian Street": ["南京路步行街", "南京路"],
  "Oriental Pearl Tower": ["东方明珠"],
  "Shanghai Tower": ["上海中心大厦", "上海中心"],
  Tianzifang: ["田子坊"],
  Xintiandi: ["新天地"],
  "Jing'an Temple": ["静安寺"],
  "Forbidden City": ["故宫", "紫禁城"],
  "Tiananmen Square": ["天安门广场", "天安门"],
  "Jingshan Park": ["景山公园"],
  "Temple of Heaven": ["天坛"],
  "Summer Palace": ["颐和园"],
  "Mutianyu Great Wall": ["慕田峪长城", "长城"],
  "West Lake": ["西湖"],
  "Lingyin Temple": ["灵隐寺"],
  "Longjing Tea Village": ["龙井茶村", "龙井村"],
  "Yalong Bay": ["亚龙湾"],
  "Wuzhizhou Island": ["蜈支洲岛"],
  "Dadonghai Beach": ["大东海"],
  "Tianya Haijiao": ["天涯海角"],
  "Shibuya Crossing": ["涩谷十字路口", "涩谷"],
  "Meiji Jingu": ["明治神宫"],
  "Senso-ji": ["浅草寺"],
  "Gyeongbokgung Palace": ["景福宫"],
  "Bukchon Hanok Village": ["北村韩屋村"],
  "Gwangjang Market": ["广藏市场"],
  Myeongdong: ["明洞"],
  "N Seoul Tower": ["首尔塔", "N首尔塔"],
  "Gardens by the Bay": ["滨海湾花园"],
  "Cloud Forest": ["云雾林"],
  "Marina Bay Sands SkyPark": ["金沙空中花园"],
  "Merlion Park": ["鱼尾狮公园"],
  "Victoria Peak": ["太平山顶"],
  "Tsim Sha Tsui Promenade": ["尖沙咀海滨长廊"],
  "Avenue of Stars": ["星光大道"],
  "Chengdu Research Base of Giant Panda Breeding": ["成都大熊猫繁育研究基地", "熊猫基地"],
  "Kuanzhai Alley": ["宽窄巷子"],
  "Jinli Ancient Street": ["锦里古街"],
  "Xi'an City Wall": ["西安城墙"],
  "Bell Tower of Xi'an": ["西安钟楼", "钟楼"],
  "Muslim Quarter": ["回民街"],
  "Terracotta Army": ["兵马俑", "秦始皇兵马俑"],
  "Elephant Trunk Hill": ["象鼻山"],
  "Two Rivers and Four Lakes": ["两江四湖"],
  "Reed Flute Cave": ["芦笛岩"],
  "The Grand Palace": ["大皇宫"],
  "Wat Phra Kaew": ["玉佛寺"],
  "Wat Arun": ["郑王庙"],
  "Patong Beach": ["芭东海滩"],
  "Big Buddha Phuket": ["普吉大佛"],
  "Phuket Old Town": ["普吉老城"],
  "Eiffel Tower": ["埃菲尔铁塔"],
  "Louvre Museum": ["卢浮宫"],
  "Arc de Triomphe": ["凯旋门"],
  Colosseum: ["罗马斗兽场", "斗兽场"],
  Pantheon: ["万神殿"],
  "Trevi Fountain": ["特莱维喷泉", "许愿池"],
  "Sagrada Familia": ["圣家堂"],
  "Casa Batllo": ["巴特罗之家"],
  "Park Guell": ["古埃尔公园"],
  "Barceloneta Beach": ["巴塞罗那塔海滩"],
  "London Eye": ["伦敦眼"],
  "British Museum": ["大英博物馆"],
  "Tower Bridge": ["塔桥"],
  "Burj Khalifa": ["哈利法塔"],
  "Dubai Mall": ["迪拜购物中心"],
  "Dubai Marina Walk": ["迪拜码头步道"],
  "Hulhumale Beach": ["胡鲁马累海滩"],
  "Oia Castle": ["伊亚城堡"],
  "Oia Blue Domes": ["伊亚蓝顶教堂"],
  "Red Beach": ["红沙滩"],
};

export const normalizeSearchText = (value: string) =>
  value
    .toLowerCase()
    .replace(/[’']/g, "")
    .replace(/[\s,，.。:：;；/\\|()[\]{}\-–_]+/g, "");

export const searchAliasesFor = (value: string) => zhAliases[value] ?? [];

export const buildSearchText = (values: Array<string | undefined>) =>
  values
    .filter(Boolean)
    .flatMap((value) => [value as string, ...searchAliasesFor(value as string)])
    .join(" ");
